- name: My first play
  hosts: virtualmachines
  remote_user: juan
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world